{% set version = "0.9.1" %}

package:
  name: hcp
  version: {{ version }}

source:
  url: https://github.com/hashicorp/hcp/archive/v{{ version }}.tar.gz
  sha256: f7867437e8da2391ff3812ded272104705cf1677cb8ca94e4292846c796aa672

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - hcp --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: HCP Command-Line Interface
  home: https://github.com/hashicorp/hcp
  dev_url: https://github.com/hashicorp/hcp

extra:
  recipe-maintainers:
    - danielnachun
