{% set version = "0.11.0" %}

package:
  name: hcp
  version: {{ version }}

source:
  url: https://github.com/hashicorp/hcp/archive/v{{ version }}.tar.gz
  sha256: d6f7c4509a3d181d52c1b219376bae58da92be637f796a9c4c497b5b93249078

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - hcp --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: HCP Command-Line Interface
  home: https://github.com/hashicorp/hcp
  dev_url: https://github.com/hashicorp/hcp

extra:
  recipe-maintainers:
    - danielnachun
