{% set version = "0.9.0" %}

package:
  name: hcp
  version: {{ version }}

source:
  url: https://github.com/hashicorp/hcp/archive/v{{ version }}.tar.gz
  sha256: f9158ccc6379ef54e7415087a6325777a7f2757f5142fbc2fd5ecb83c04a2480

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - hcp --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: HCP Command-Line Interface
  home: https://github.com/hashicorp/hcp
  dev_url: https://github.com/hashicorp/hcp

extra:
  recipe-maintainers:
    - danielnachun
